import type { NextPage } from "next";
import React, { useEffect } from "react";
import Router from "next/router";
import Head from "next/head";
import Caution from "../components/Caution";
import Desc from "../components/Desc";
import Go from "../components/Go";
import Top from "../components/Top";

const Home: NextPage = () => {
  useEffect(() => {
    if (
      navigator.userAgent.indexOf("iPhone") > 0 ||
      (navigator.userAgent.indexOf("Android") > 0 &&
        navigator.userAgent.indexOf("Mobile") > 0)
    ) {
      // スマートフォン向けの記述
    } else {
      Router.push("/except");
    }
  }, []);

  return (
    <div>
      <Head>
        <title>はじめまして！そしまるです！</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Top />

        <Desc />

        <Caution />

        <Go />
      </main>
    </div>
  );
};

export default Home;
